FROM python:3.9-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app

# set the working directory
WORKDIR /app


# install dependencies
COPY requirements.txt /app/

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app

EXPOSE 8080

ENTRYPOINT ["streamlit", "run", "src/studentsproject/streamlit_app.py", "--server.port=8080", "--server.address=0.0.0.0"]

